export { HomePage } from './HomePage'
export { Login } from './Login'
export { SignUp } from './SignUp'
export { OrdersPage } from './OrdersPage' 
export { NewOrderPage } from './NewOrderPage'
export { OrderPage} from './OrderPage'
export {NewEmployee} from './NewEmployeePage'
export {Emplpyees} from './EmployeesPage'
export {NewSite} from './RegistroPlantaPage'
export {Plantas} from './PlantasPage'
export {NewMachine} from './RegistroMaquinaPage'
export {Machines} from './MaquinasPage'
export {NewBill} from './NewFacturaPage'
export {Inventory} from './InventoryPage'
export {NewPiece} from './NewPiece'
export { NotFound } from './404'