export { HomePage } from './HomePage'
export { SignUp } from './SignUp'
export { OrdersPage } from './OrdersPage' 
export { NewOrderPage } from './NewOrderPage'
export { OrderPage} from './OrderPage'
export { NotFound } from './404'